image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - version
  - build
  - test
  - pack
  - publish

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "true"
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

cache:
  key: "scte35-net-${CI_COMMIT_REF_SLUG}"
  paths:
    - .nuget/packages
    - src/**/obj
    - src/**/bin
    - tests/**/obj
    - tests/**/bin

version:
  stage: version
  script:
    - dotnet --info
    - dotnet tool install --global Versionize || true
    - bash .gitlab/versionize.sh
  artifacts:
    reports:
      dotenv: version.env

build:
  stage: build
  needs: [version]
  script:
    - dotnet restore
    - dotnet build -c Release -p:ContinuousIntegrationBuild=true -p:Version="$VERSION" -p:InformationalVersion="$VERSION"
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - src/**/bin/Release
      - tests/**/bin/Release

test:
  stage: test
  needs: [build]
  script:
    - dotnet test -c Release --no-build --logger "trx;LogFileName=test_results.trx" --collect:"XPlat Code Coverage"
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: tests/**/TestResults/*.trx
    paths:
      - tests/**/TestResults
  coverage: '/Total\s*Lines:\s*\d+.\d+\%/i'

pack:
  stage: pack
  needs: [test]
  script:
    - dotnet pack -c Release -p:ContinuousIntegrationBuild=true -p:PackageVersion="$VERSION" -o ./artifacts
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - artifacts/*.nupkg
      - artifacts/*.snupkg

publish:
  stage: publish
  needs: [pack]
  script:
    - 'test "$DID_RELEASE" = "true" || { echo "No release this pipeline (DID_RELEASE=$DID_RELEASE). Skipping publish."; exit 0; }'
    - 'test -n "$NUGET_SOURCE" || { echo "NUGET_SOURCE not set; skipping publish."; exit 0; }'
    - 'test -n "$NUGET_API_KEY" || { echo "NUGET_API_KEY not set; skipping publish."; exit 0; }'
    - echo "Publishing $RELEASE_TAG -> $NUGET_SOURCE"
    - dotnet nuget push "artifacts/*.nupkg" --api-key "$NUGET_API_KEY" --source "$NUGET_SOURCE" --skip-duplicate
  rules:
    - if: '$DID_RELEASE == "true"'
      when: on_success
    - when: never