using Scte35.Net.Constants;

namespace Scte35.Net.Model.Enums;

public enum SegmentationType : byte
{
    NotIndicated = Scte35Constants.SegmentationTypeNotIndicated,
    ContentIdentification = Scte35Constants.SegmentationTypeContentIdentification,
    ProgramStart = Scte35Constants.SegmentationTypeProgramStart,
    ProgramEnd = Scte35Constants.SegmentationTypeProgramEnd,
    ProgramEarlyTermination = Scte35Constants.SegmentationTypeProgramEarlyTermination,
    ProgramBreakaway = Scte35Constants.SegmentationTypeProgramBreakaway,
    ProgramResumption = Scte35Constants.SegmentationTypeProgramResumption,
    ProgramRunoverPlanned = Scte35Constants.SegmentationTypeProgramRunoverPlanned,
    ProgramRunoverUnplanned = Scte35Constants.SegmentationTypeProgramRunoverUnplanned,
    ProgramOverlapStart = Scte35Constants.SegmentationTypeProgramOverlapStart,
    ProgramBlackoutOverride = Scte35Constants.SegmentationTypeProgramBlackoutOverride,
    ProgramStartInProgress = Scte35Constants.SegmentationTypeProgramStartInProgress,
    ChapterStart = Scte35Constants.SegmentationTypeChapterStart,
    ChapterEnd = Scte35Constants.SegmentationTypeChapterEnd,
    BreakStart = Scte35Constants.SegmentationTypeBreakStart,
    BreakEnd = Scte35Constants.SegmentationTypeBreakEnd,
    OpeningCreditStart = Scte35Constants.SegmentationTypeOpeningCreditStart,
    OpeningCreditEnd = Scte35Constants.SegmentationTypeOpeningCreditEnd,
    ClosingCreditStart = Scte35Constants.SegmentationTypeClosingCreditStart,
    ClosingCreditEnd = Scte35Constants.SegmentationTypeClosingCreditEnd,
    ProviderAdStart = Scte35Constants.SegmentationTypeProviderAdStart,
    ProviderAdEnd = Scte35Constants.SegmentationTypeProviderAdEnd,
    DistributorAdStart = Scte35Constants.SegmentationTypeDistributorAdStart,
    DistributorAdEnd = Scte35Constants.SegmentationTypeDistributorAdEnd,
    ProviderPOStart = Scte35Constants.SegmentationTypeProviderPOStart,
    ProviderPOEnd = Scte35Constants.SegmentationTypeProviderPOEnd,
    DistributorPOStart = Scte35Constants.SegmentationTypeDistributorPOStart,
    DistributorPOEnd = Scte35Constants.SegmentationTypeDistributorPOEnd,
    ProviderOverlayPOStart = Scte35Constants.SegmentationTypeProviderOverlayPOStart,
    ProviderOverlayPOEnd = Scte35Constants.SegmentationTypeProviderOverlayPOEnd,
    DistributorOverlayPOStart = Scte35Constants.SegmentationTypeDistributorOverlayPOStart,
    DistributorOverlayPOEnd = Scte35Constants.SegmentationTypeDistributorOverlayPOEnd,
    ProviderPromoStart = Scte35Constants.SegmentationTypeProviderPromoStart,
    ProviderPromoEnd = Scte35Constants.SegmentationTypeProviderPromoEnd,
    DistributorPromoStart = Scte35Constants.SegmentationTypeDistributorPromoStart,
    DistributorPromoEnd = Scte35Constants.SegmentationTypeDistributorPromoEnd,
    UnscheduledEventStart = Scte35Constants.SegmentationTypeUnscheduledEventStart,
    UnscheduledEventEnd = Scte35Constants.SegmentationTypeUnscheduledEventEnd,
    AltConOppStart = Scte35Constants.SegmentationTypeAltConOppStart,
    AltConOppEnd = Scte35Constants.SegmentationTypeAltConOppEnd,
    ProviderAdBlockStart = Scte35Constants.SegmentationTypeProviderAdBlockStart,
    ProviderAdBlockEnd = Scte35Constants.SegmentationTypeProviderAdBlockEnd,
    DistributorAdBlockStart = Scte35Constants.SegmentationTypeDistributorAdBlockStart,
    DistributorAdBlockEnd = Scte35Constants.SegmentationTypeDistributorAdBlockEnd,
    NetworkStart = Scte35Constants.SegmentationTypeNetworkStart,
    NetworkEnd = Scte35Constants.SegmentationTypeNetworkEnd,
}