name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git author
        run: |
          git config --global user.email "mirror-bot@users.noreply.github.com"
          git config --global user.name  "GitHub Mirror Bot"

      - name: Add GitLab remote
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/gringo-go-go/scte35.net.git
          git remote -v

      - name: Push branches and tags (avoid --mirror)
        run: |
          # Push all branches
          git push --prune gitlab +refs/heads/*:refs/heads/*
          # Push all tags
          git push --prune gitlab +refs/tags/*:refs/tags/*
